export const moduleMeta: Record<string, { title: string; subtitle: string; emptyHeading: string; emptyBody: string; cta?: string }> = {
  dashboard: {
    title: "Trust Readiness Dashboard",
    subtitle: "Live overview of compliance, risk, evidence, incidents, and integration posture for your organization.",
    emptyHeading: "Complete onboarding to unlock your score",
    emptyBody: "Your dashboard will populate automatically from real activities, evidence, incidents, and integration syncs.",
    cta: "Go to Onboarding",
  },
  frameworks: {
    title: "Compliance Framework Registry",
    subtitle: "Manage reviewed framework packs for Kenya DPA, GDPR, SOC 2 readiness, and ISO 27001 readiness.",
    emptyHeading: "No framework packs reviewed yet",
    emptyBody: "Create or upload framework packs with versioning, source references, and reviewer sign-off.",
    cta: "Add Framework",
  },
  "kenya-dpa": {
    title: "Kenya DPA Readiness",
    subtitle: "Track controller-processor classification, ODPC readiness, rights workflows, and safeguards.",
    emptyHeading: "No Kenya DPA assessment started",
    emptyBody: "Start assessment and attach supporting evidence for each control area.",
    cta: "Start Kenya DPA Assessment",
  },
  gdpr: {
    title: "GDPR Readiness",
    subtitle: "Track lawful basis, Article 30 records, transfer governance, and rights operations.",
    emptyHeading: "No GDPR assessment started",
    emptyBody: "Begin with data inventory and processing records before running score calculations.",
    cta: "Start GDPR Assessment",
  },
  soc2: {
    title: "SOC 2 Readiness",
    subtitle: "Prepare Trust Services Criteria evidence and ownership for audit readiness.",
    emptyHeading: "No SOC 2 readiness run found",
    emptyBody: "Assign control owners and collect implementation evidence before auditor export.",
    cta: "Start SOC 2 Readiness",
  },
  iso27001: {
    title: "ISO 27001 Readiness",
    subtitle: "Build ISMS artifacts, risk register coverage, and SoA traceability.",
    emptyHeading: "No ISO 27001 readiness run found",
    emptyBody: "Create risk entries and attach policy and control evidence to assess maturity.",
    cta: "Start ISO 27001 Readiness",
  },
  "data-inventory": {
    title: "Data Inventory and RoPA",
    subtitle: "Maintain processing activities, lawful basis, data categories, and transfer paths.",
    emptyHeading: "No processing activities recorded",
    emptyBody: "Add your first processing activity to begin RoPA and retention governance.",
    cta: "Add Processing Activity",
  },
  dpia: {
    title: "DPIA Workspace",
    subtitle: "Screen high-risk processing and document mitigation with versioned approvals.",
    emptyHeading: "No DPIA records yet",
    emptyBody: "Run a screening questionnaire for sensitive or large-scale processing activities.",
    cta: "Create DPIA",
  },
  dsr: {
    title: "Data Subject Requests",
    subtitle: "Track access, deletion, correction, portability, objection, and restriction workflows.",
    emptyHeading: "No requests submitted",
    emptyBody: "Requests from real users will appear here with due dates and verification state.",
  },
  incidents: {
    title: "Incident and Breach Desk",
    subtitle: "Manage breach classification, impact analysis, and regulator notification readiness.",
    emptyHeading: "No incidents opened",
    emptyBody: "Create incident records to trigger timeline tracking and breach-clock response.",
    cta: "Create Incident",
  },
  vendors: {
    title: "Vendor Risk Register",
    subtitle: "Track third-party data processors, DPA status, security reviews, and renewal risk.",
    emptyHeading: "No vendors listed",
    emptyBody: "Add processors and subprocessors to build your vendor governance program.",
    cta: "Add Vendor",
  },
  evidence: {
    title: "Evidence Vault",
    subtitle: "Collect uploaded, API-synced, and attested evidence with hash, versioning, and approvals.",
    emptyHeading: "No evidence collected",
    emptyBody: "Upload your first document or connect an integration to start control mapping.",
    cta: "Upload Evidence",
  },
  policies: {
    title: "Policy Center",
    subtitle: "Draft, review, approve, and acknowledge privacy and security policies with legal gates.",
    emptyHeading: "No policy documents yet",
    emptyBody: "Create policy drafts and route legal-sensitive content for legal review.",
    cta: "Create Policy",
  },
  reports: {
    title: "Report Engine",
    subtitle: "Generate Kenya DPA, GDPR, SOC 2, ISO 27001, and board-level readiness reports.",
    emptyHeading: "No reports generated",
    emptyBody: "Generate reports from real organization data and export as PDF, DOCX, CSV, and JSON.",
    cta: "Generate Report",
  },
  "security-posture": {
    title: "Security Posture Review",
    subtitle: "Run integration-based checks and web posture reviews for practical security evidence.",
    emptyHeading: "No integration findings yet",
    emptyBody: "Connect GitHub or run an application check URL to begin posture analysis.",
    cta: "Run Security Check",
  },
  integrations: {
    title: "Integrations",
    subtitle: "Connect data sources for automated evidence, findings, alerts, and sync history.",
    emptyHeading: "No active integrations",
    emptyBody: "Connect GitHub first for automated posture findings. Others can remain manual until configured.",
    cta: "Connect Integration",
  },
  tasks: {
    title: "Compliance Tasks",
    subtitle: "Assign controls, due dates, priority, reminders, and completion approvals.",
    emptyHeading: "No tasks assigned",
    emptyBody: "Create tasks to track remediation, evidence collection, and review ownership.",
    cta: "Create Task",
  },
  "trust-center": {
    title: "Trust Center",
    subtitle: "Publish approved documents and posture summaries for customer reviewers.",
    emptyHeading: "No trust pages published",
    emptyBody: "Create trust pages and approve documents before they appear on public views.",
    cta: "Create Trust Page",
  },
  billing: {
    title: "Billing and Subscription",
    subtitle: "Manage plan entitlements and monitor live provider state when billing is configured.",
    emptyHeading: "Billing provider not configured",
    emptyBody: "Set STRIPE_SECRET_KEY in backend environment to enable live subscriptions.",
  },
  "audit-logs": {
    title: "Audit Trail",
    subtitle: "Review sensitive actions, evidence changes, and governance events by organization.",
    emptyHeading: "No audit logs captured yet",
    emptyBody: "Logs appear when users create organizations, upload evidence, run syncs, and update workflows.",
  },
  settings: {
    title: "Workspace Settings",
    subtitle: "Manage organization profile, role controls, retention preferences, and security settings.",
    emptyHeading: "No additional settings configured",
    emptyBody: "Add profile data and workflow defaults as your governance program matures.",
  },
};
